name: Publish

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g npm
        working-directory: node
      - run: npm ci
        working-directory: node
      - run: node test/run.js --github
        working-directory: node

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: aspiesoft
      - run: npm install -g npm
        working-directory: node
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: node

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: aspiesoft
      - run: npm install -g npm
        working-directory: node
      - run: npm publish
        env:
          AUTHOR_EMAIL: aspiesoftweb@gmail.com
          AUTHOR_NAME: aspiesoft
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
        working-directory: node

  publish-npm-noscope:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: remove scope from package name
        run: |
          sed -i 's/"name":\s"@aspiesoft\//"name":"/g' package.json
          sed -i 's/"name":\s"@aspiesoft\//"name":"/g' package-lock.json
        working-directory: node
      - run: npm install -g npm
        working-directory: node
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        working-directory: node
